name: Documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-deploy:
    name: Build Documentation and Push
    runs-on: ubuntu-latest
    steps:

      # https://github.com/marketplace/actions/checkout
      - name: Start actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          playwright install --with-deps chromium

      - name: Make Docs
        shell: bash -l {0}
        run: |
          jupyter-book build tcs/ --builder pdfhtml
          cp tcs/_build/pdf/book.pdf tcs/book.pdf
          jupyter-book build tcs/
          
      # Great extra actions to compose with:
      # Create an artifact of the html output.
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: tcs/_build/html/

      - name: Commit documentation changes
        shell: bash -l {0}
        run: |
          git clone https://github.com/williameaton/Theoretical_and_Computational_Seismology --branch gh-pages --single-branch gh-pages
          cd gh-pages
          git pull origin gh-pages  # Ensure the local branch is up-to-date
          cd ..
          rm -rf gh-pages/*
          cp -r tcs/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true  # Force push to overwrite remote branch